package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
)

const (
	stylesSourceFile = "cmd/gendoc/styles.go"
	chromaRepoURL    = "https://github.com/alecthomas/chroma.git"
	chromaTempDir    = "/tmp/chroma-latest"
	chromaStylesPath = "/tmp/chroma-latest/styles"
)

type styleInfo struct {
	fileName  string // e.g., "aura-theme-dark"
	styleName string // e.g., "Aura Theme Dark"
}

func fetchLatestChromaStyles() error {
	// Remove old temp directory if it exists
	os.RemoveAll(chromaTempDir)

	log.Println("Cloning latest chroma repository from master branch...")

	// Clone the latest chroma repository (shallow clone, master branch only)
	_, err := git.PlainClone(chromaTempDir, false, &git.CloneOptions{
		URL:           chromaRepoURL,
		ReferenceName: plumbing.NewBranchReferenceName("master"),
		SingleBranch:  true,
		Depth:         1,
		Progress:      os.Stdout,
	})

	if err != nil {
		return fmt.Errorf("failed to clone chroma repo: %w", err)
	}

	log.Println("Successfully cloned latest chroma repository")
	return nil
}

func generateGoSourceCode(styles []styleInfo) string {
	var buffer bytes.Buffer
	buffer.WriteString("package main\n\n")
	buffer.WriteString("// This file is auto-generated by cmd/selfupdate\n")
	buffer.WriteString("// It maps XML filenames to the actual style names registered in chroma\n\n")

	buffer.WriteString("type styleMapping struct {\n")
	buffer.WriteString("\tfileName  string // XML filename without .xml extension\n")
	buffer.WriteString("\tstyleName string // Style name as defined in the XML\n")
	buffer.WriteString("}\n\n")

	buffer.WriteString("var styles = []styleMapping{\n")
	for _, style := range styles {
		buffer.WriteString(fmt.Sprintf("\t{fileName: \"%s\", styleName: \"%s\"},\n", style.fileName, style.styleName))
	}
	buffer.WriteString("}\n")
	return buffer.String()
}

func main() {
	// Fetch the absolute latest styles from GitHub master branch
	if err := fetchLatestChromaStyles(); err != nil {
		log.Fatalf("error fetching latest chroma styles: %v", err)
	}

	// Ensure cleanup happens even if we panic
	defer os.RemoveAll(chromaTempDir)

	// Walk through the freshly cloned styles directory
	var styleInfos []styleInfo

	err := filepath.Walk(chromaStylesPath, func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".xml") {
			return nil
		}

		fileName := strings.TrimSuffix(filepath.Base(path), ".xml")

		// Read the XML to get the style name
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		// Parse style name from XML: <style name="...">
		styleNameStart := bytes.Index(data, []byte(`<style name="`))
		if styleNameStart == -1 {
			log.Printf("Warning: Could not find style name in %s\n", path)
			return nil
		}

		styleNameStart += len(`<style name="`)
		styleNameEnd := bytes.Index(data[styleNameStart:], []byte(`"`))
		if styleNameEnd == -1 {
			log.Printf("Warning: Could not parse style name in %s\n", path)
			return nil
		}

		styleName := string(data[styleNameStart : styleNameStart+styleNameEnd])

		styleInfos = append(styleInfos, styleInfo{
			fileName:  fileName,
			styleName: styleName,
		})

		return nil
	})

	if err != nil {
		log.Fatalf("error walking styles directory: %v", err)
	}

	// Sort by filename for consistent output
	sort.Slice(styleInfos, func(i, j int) bool {
		return styleInfos[i].fileName < styleInfos[j].fileName
	})

	sourceCode := generateGoSourceCode(styleInfos)

	fmt.Println(sourceCode)

	err = os.WriteFile(stylesSourceFile, []byte(sourceCode), 0644)
	if err != nil {
		log.Fatalf("error writing source code to file: %v", err)
	}

	log.Printf("Successfully updated %s with %d styles from latest chroma master\n", stylesSourceFile, len(styleInfos))
}
